# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    # TNF 5:45 AM UTC / 12:45 AM ET
    - cron:  '45 5 * 1,2,9-12 5'
    # Early window: 10:15 PM UTC / 5:15 PM ET
    - cron:  '15 22 * 1,2,9-12 0'
    # Late window: 0:20 UTC / 8:20 ET
    - cron:  '20 0 * 1,2,9-12 1'
    # SNF/MNF: 5:45 UTC / 12:45 ET
    - cron:  '45 5 * 1,2,9-12 1'
    - cron:  '45 5 * 1,2,9-12 2'
  workflow_dispatch:

name: ep-update-data

jobs:
  ep-update-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ github.token }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            ropensci/piggyback
            arrow
            readr
            nflverse/nflreadr
      - name: Run data update
        run: |
          Rscript -e 'source("update/ep_update.R")'
        shell: bash
